import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Activity, BookOpen, ChevronRight, Cpu, Download, FileText, Folder, FolderOpen, Gauge, HardDrive, Layers3, Maximize2, Minimize2, Network, Plus, RefreshCw, Search, Server, Settings, Shield, SquareTerminal, Trash2, Upload, Wifi, X } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";

type NodeType = "dir" | "file";
type FSNode = { type: NodeType; name: string; mode: string; owner: string; group: string; content?: string; children?: Record<string, FSNode> };
type UserName = "guest" | "user" | "admin" | "root";
type TerminalLine = { id: number; kind: "input" | "output" | "error" | "system"; text: string };
type Session = { id: string; title: string; user: UserName; cwd: string; input: string; history: string[]; historyIndex: number; env: Record<string, string>; aliases: Record<string, string>; lines: TerminalLine[]; shellStack: string[]; passwordMode?: UserName | null; passwordTarget?: UserName | null };

const COMMANDS = ["alias","apt","apt-get","awk","banner","bash","bg","cat","cd","chmod","chown","clear","cp","curl","date","df","dig","dpkg","du","echo","env","exit","export","fastfetch","fg","find","free","grep","groups","gunzip","head","help","history","hostname","htop","id","ifconfig","ip","jobs","kill","less","ls","lsblk","lscpu","lspci","lsusb","matrix","mkdir","motd","mv","nano","neofetch","netstat","network","nslookup","passwd","ping","pkill","printenv","ps","pwd","reboot","rm","rmdir","route","service","shutdown","ss","su","sudo","sysinfo","systemctl","tail","tar","timedatectl","top","touch","tracepath","traceroute","uname","unzip","uptime","users","wget","whoami","which","zip"];
const USERS: Record<UserName, { uid:number; gid:number; groups:string[]; home:string; shell:string; password:string }> = {
  guest:{uid:1001,gid:1001,groups:["guest"],home:"/home/guest",shell:"/bin/bash",password:"guest"}, user:{uid:1000,gid:1000,groups:["users","sudo"],home:"/home/henry",shell:"/bin/bash",password:"henry"}, admin:{uid:900,gid:900,groups:["admin","sudo","users"],home:"/home/admin",shell:"/bin/bash",password:"admin"}, root:{uid:0,gid:0,groups:["root","sudo","admin"],home:"/root",shell:"/bin/bash",password:"root"}
};
const dir=(name:string,owner="root",group="root",children:Record<string,FSNode>={}):FSNode=>({type:"dir",name,mode:"drwxr-xr-x",owner,group,children});
const file=(name:string,content="",owner="root",group="root",mode="-rw-r--r--"):FSNode=>({type:"file",name,mode,owner,group,content});
const initialFiles:FSNode=dir("/","root","root",{
  bin:dir("bin","root","root",{bash:file("bash","ELF 64-bit virtual bash binary","root","root","-rwxr-xr-x"),sh:file("sh","ELF 64-bit virtual sh binary","root","root","-rwxr-xr-x")}), boot:dir("boot","root","root",{"vmlinuz-6.8.0":file("vmlinuz-6.8.0","Ubuntu virtual kernel 6.8.0")}), dev:dir("dev"),
  etc:dir("etc","root","root",{hostname:file("hostname","henry\n"),"os-release":file("os-release","PRETTY_NAME=\"Ubuntu Simulator\"\nNAME=\"Ubuntu\"\nVERSION=\"24.04 LTS (Noble Numbat)\"\n"),hosts:file("hosts","127.0.0.1 localhost\n127.0.1.1 henry\n")}),
  home:dir("home","root","root",{henry:dir("henry","user","users",{Desktop:dir("Desktop","user","users"),Documents:dir("Documents","user","users",{"welcome.txt":file("welcome.txt","Welcome to henry's Ubuntu simulator.\n","user","users")}),Downloads:dir("Downloads","user","users"),Pictures:dir("Pictures","user","users"),Videos:dir("Videos","user","users")}),guest:dir("guest","guest","guest"),admin:dir("admin","admin","admin")}),
  lib:dir("lib"),media:dir("media"),mnt:dir("mnt"),opt:dir("opt"),proc:dir("proc"),root:dir("root","root","root",{".bashrc":file(".bashrc","# root shell configuration\n","root","root","-rw-------")}),run:dir("run"),sbin:dir("sbin"),srv:dir("srv"),sys:dir("sys"),tmp:dir("tmp","root","root"),
  usr:dir("usr","root","root",{bin:dir("bin"),local:dir("local"),share:dir("share")}),var:dir("var","root","root",{log:dir("log","root","root",{syslog:file("syslog","Aug 30 17:50 henry systemd[1]: Starting simulated services...\n","root","adm","-rw-r-----")}),www:dir("www")})
});
const cloneFS=(node:FSNode):FSNode=>JSON.parse(JSON.stringify(node));
const splitPath=(p:string)=>p.split("/").filter(Boolean);
function resolvePath(cwd:string,target="."){const raw=target.startsWith("/")?target:`${cwd}/${target}`;const parts:string[]=[];raw.split("/").forEach(p=>{if(!p||p===".")return;if(p==="..")parts.pop();else parts.push(p)});return "/"+parts.join("/");}
function getNode(root:FSNode,path:string):FSNode|null{if(path==="/")return root;let cur=root;for(const p of splitPath(path)){if(cur.type!=="dir"||!cur.children?.[p])return null;cur=cur.children[p]}return cur;}
function getParent(root:FSNode,path:string){const normalized=resolvePath("/",path),parts=splitPath(normalized),name=parts.pop()||"",parentPath="/"+parts.join("/");return {parent:getNode(root,parentPath||"/"),name,parentPath:parentPath||"/"};}
function formatPrompt(user:UserName,cwd:string){const display=user==="root"?(cwd==="/root"||cwd==="/"?"~":cwd):(cwd===USERS[user].home?"~":cwd);return `${user}@henry:${display}${user==="root"?"#":"$"}`;}
function tokenize(input:string){const tokens:string[]=[];let cur="",quote:"'"|'"'|null=null;for(let i=0;i<input.length;i++){const ch=input[i];if(ch==="\\"&&i+1<input.length){cur+=input[++i];continue}if(quote){if(ch===quote)quote=null;else cur+=ch;continue}if(ch==="'"||ch==='"'){quote=ch;continue}if(/\s/.test(ch)){if(cur){tokens.push(cur);cur=""}continue}if([">","|",";","&"].includes(ch)){if(cur){tokens.push(cur);cur=""}if(ch===">"&&input[i+1]===">"){tokens.push(">>");i++}else if(ch==="&"&&input[i+1]==="&"){tokens.push("&&");i++}else tokens.push(ch);continue}cur+=ch}if(cur)tokens.push(cur);return tokens;}
function expandVars(v:string,s:Session){return v.replace(/\$(\w+|\{[^}]+\})/g,(_,raw)=>{const k=raw.startsWith("{")?raw.slice(1,-1):raw;if(k==="HOME")return USERS[s.user].home;if(k==="USER")return s.user;if(k==="PWD")return s.cwd;return s.env[k]??""});}
const line=(kind:TerminalLine["kind"],text:string,idRef:{value:number}):TerminalLine=>({id:idRef.value++,kind,text});
function getSavedFS(){try{const raw=localStorage.getItem("henry-linux-fs");return raw?JSON.parse(raw):cloneFS(initialFiles)}catch{return cloneFS(initialFiles)}}
function getInitialSession():Session{return{id:crypto.randomUUID(),title:"henry",user:"user",cwd:"/",input:"",history:[],historyIndex:-1,env:{LANG:"en_US.UTF-8",SHELL:"/bin/bash",TERM:"xterm-256color",EDITOR:"nano",PATH:"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"},aliases:{},lines:[{id:1,kind:"system",text:"Ubuntu Simulator 24.04 LTS · kernel 6.8.0-virtual · bash 5.2"},{id:2,kind:"system",text:"Safe browser sandbox: system commands never execute on your computer."},{id:3,kind:"system",text:"Type `help` for commands. Try `neofetch`, `ls -la`, or `curl https://api.github.com`."}],shellStack:[]};}
const BASE_PROCESSES=[[1,"root","0.0","0.1","systemd --system"],[412,"root","0.1","0.4","systemd-journald"],[621,"root","0.0","0.2","NetworkManager"],[731,"root","0.2","0.7","sshd: /usr/sbin/sshd"],[1042,"user","1.3","2.1","bash"],[1180,"user","0.5","1.0","terminal-ui"]];

export default function App(){
 const [fs,setFs]=useState<FSNode>(()=>getSavedFS()); const [sessions,setSessions]=useState<Session[]>(()=>[getInitialSession()]); const [activeId,setActiveId]=useState(""); const [panel,setPanel]=useState<"files"|"processes"|"system"|"network"|"settings"|null>(null); const [searchOpen,setSearchOpen]=useState(false); const [searchQuery,setSearchQuery]=useState(""); const [fullscreen,setFullscreen]=useState(false); const [nano,setNano]=useState<{path:string;content:string}|null>(null); const terminalRef=useRef<HTMLDivElement>(null); const inputRef=useRef<HTMLInputElement>(null); const idRef=useRef(100);
 useEffect(()=>{if(!activeId&&sessions[0])setActiveId(sessions[0].id)},[activeId,sessions]); const active=sessions.find(s=>s.id===activeId)||sessions[0];
 const persistFS=useCallback((next:FSNode)=>{setFs(next);try{localStorage.setItem("henry-linux-fs",JSON.stringify(next))}catch{}},[]);
 const updateActive=useCallback((patch:Partial<Session>)=>setSessions(c=>c.map(s=>s.id===activeId?{...s,...patch}:s)),[activeId]);
 const appendOutput=useCallback((text:string,kind:TerminalLine["kind"]="output")=>setSessions(c=>c.map(s=>s.id===activeId?{...s,lines:[...s.lines,...text.split("\n").map(t=>line(kind,t,idRef))]}:s)),[activeId]);
 useEffect(()=>{terminalRef.current?.scrollTo({top:terminalRef.current.scrollHeight,behavior:"smooth"})},[active?.lines.length]);
 const autoComplete=useCallback(()=>{const raw=active.input,last=raw.split(/\s+/).pop()||"";if(!last)return;const m=COMMANDS.filter(c=>c.startsWith(last));if(m.length===1&&!raw.includes(" "))updateActive({input:raw.slice(0,-last.length)+m[0]+" "});else if(m.length>1&&!raw.includes(" "))appendOutput(m.join("  "));else{const prefix=last.includes("/")?last.slice(last.lastIndexOf("/")+1):last,base=last.includes("/")?last.slice(0,last.lastIndexOf("/")+1):"",n=getNode(fs,resolvePath(active.cwd,base||".")),items=n?.children?Object.keys(n.children).filter(x=>x.startsWith(prefix)):[];if(items.length===1)updateActive({input:raw.slice(0,-prefix.length)+items[0]+(n?.children?.[items[0]]?.type==="dir"?"/":" ")});else if(items.length>1)appendOutput(items.join("  "))}},[active,fs,updateActive,appendOutput]);

 const executeSimple=async(argv:string[],stdin=""):Promise<{output:string;error?:boolean;nextFs?:FSNode;nextSession?:Partial<Session>;stop?:boolean}>=>{if(!argv[0])return{output:""};const command=expandVars(argv[0],active),args=argv.slice(1).map(a=>expandVars(a,active)),work=cloneFS(fs),user=active.user,priv=user==="root";
  if(active.aliases[command]&&!args.length)return executeSimple(tokenize(active.aliases[command]),stdin);
  switch(command){
   case "help":return{output:"Core: ls cd pwd mkdir rmdir touch cat less head tail cp mv rm find grep nano clear history\nShell: bash sh sudo su exit echo export env printenv alias\nSystem: uname hostname uptime free df du lsblk lscpu lspci lsusb ps top htop\nNetwork: ip ifconfig ping traceroute tracepath curl wget dig nslookup host netstat ss route\nPackages: apt apt-get dpkg · Services: systemctl service journalctl · Users: whoami id users groups passwd chmod chown kill pkill jobs bg fg\nSpecial: neofetch fastfetch matrix banner motd sysinfo network about"};
   case "about":return{output:"henry · Ubuntu Simulator\nA Linux-like command environment running entirely in the browser.\nVirtual filesystem: localStorage · Network: browser fetch only · Host OS: never accessed."};
   case "motd":return{output:"Welcome to Ubuntu Simulator.\n\n * Documentation: help\n * Safe sandbox: no host commands\n * Persistence: localStorage enabled"};
   case "banner":return{output:" _   _ _____ _   _ ______   __\n| | | | ____| | | |  _  \\ \\ / /\n| |_| | |__ | | | | | | |\\ V /\n|  _  |  __|| | | | | | | > <\n| | | | |___| |_| | |/ / / . \\ \n\\_| |_/____/ \\___/|___/ /_/ \\_\\"};
   case "matrix":return{output:"0 1 1 0 0 1 0 1 1 0 1\n1 0 0 1 1 0 1 0 1 0 0\n0 1 0 1 0 0 1 1 0 1 1\n1 1 1 0 1 0 0 1 1 0 1"};
   case "neofetch":case "fastfetch":return{output:`user@henry                     Ubuntu Simulator 24.04 LTS\n-------------------            ---------------------------\nOS: Ubuntu Simulator x86_64\nHost: Browser Virtual Machine\nKernel: 6.8.0-virtual\nShell: ${active.env.SHELL.split("/").pop()}\nTerminal: xterm-256color\nCPU: Virtual CPU (8 cores)\nMemory: 16 GiB (3.4 GiB / 16 GiB)\nDisk: 128 GiB virtual disk\nUptime: 02:14:37\nPackages: 1842 (apt)\nResolution: ${window.innerWidth}x${window.innerHeight}\nTheme: Henry Dark\nNetwork: browser bridge online`};
   case "sysinfo":return{output:`Hostname: henry\nOS: Ubuntu Simulator 24.04 LTS\nKernel: 6.8.0-virtual\nArchitecture: x86_64\nCPU: 8 vCPU\nRAM: 16 GiB\nStorage: 128 GiB virtual disk\nShell: ${active.env.SHELL}\nInit: systemd (simulated)`};
   case "network":return{output:"Interface  State     Address\nlo         UP        127.0.0.1/8\neth0       UP        192.168.1.42/24\n             gateway  192.168.1.1\n             dns      1.1.1.1, 8.8.8.8"};
   case "whoami":return{output:user}; case "id":return{output:`uid=${USERS[user].uid}(${user}) gid=${USERS[user].gid}(${user}) groups=${USERS[user].groups.join(",")}`}; case "users":return{output:"user admin guest"}; case "groups":return{output:USERS[user].groups.join(" ")}; case "hostname":return{output:"henry"}; case "pwd":return{output:active.cwd};
   case "cd":{const target=args[0]||"~",p=target==="~"?USERS[user].home:resolvePath(active.cwd,target),n=getNode(fs,p);return n?.type==="dir"?{output:"",nextSession:{cwd:p}}:{output:`bash: cd: ${target}: No such file or directory`,error:true};}
   case "ls":{const flags=args.filter(a=>a.startsWith("-")),all=flags.some(f=>f.includes("a")),long=flags.some(f=>f.includes("l")),target=args.find(a=>!a.startsWith("-"))||active.cwd,p=target==="~"?USERS[user].home:resolvePath(active.cwd,target),n=getNode(fs,p);if(!n||n.type!=="dir")return{output:`ls: cannot access '${target}': No such file or directory`,error:true};const es=Object.values(n.children||{}).filter(x=>all||!x.name.startsWith("."));return{output:long?es.map(x=>`${x.mode}  1 ${x.owner.padEnd(6)} ${x.group.padEnd(6)} ${String((x.content||"").length).padStart(5)} Aug 30 17:50 ${x.name}${x.type==="dir"?"/":""}`).join("\n"):es.map(x=>x.name+(x.type==="dir"?"/":"")).join("  ")};}
   case "mkdir":{const targets=args.filter(a=>!a.startsWith("-"));if(!targets.length)return{output:"mkdir: missing operand",error:true};for(const raw of targets){const p=resolvePath(active.cwd,raw),{parent,name}=getParent(work,p);if(!parent?.children)return{output:`mkdir: cannot create directory '${raw}'`,error:true};if(!priv&&parent.owner!==user)return{output:"mkdir: permission denied",error:true};parent.children[name]=dir(name,user,USERS[user].groups[0]);}return{output:"",nextFs:work};}
   case "rmdir":case "rm":{const recursive=args.some(a=>a.includes("r")),targets=args.filter(a=>!a.startsWith("-"));if(!targets.length)return{output:`${command}: missing operand`,error:true};for(const raw of targets){const p=resolvePath(active.cwd,raw),{parent,name}=getParent(work,p),n=getNode(work,p);if(!n||!parent?.children)return{output:`${command}: cannot remove '${raw}': No such file or directory`,error:true};if(n.type==="dir"&&!recursive)return{output:`${command}: cannot remove '${raw}': Is a directory`,error:true};delete parent.children[name];}return{output:"",nextFs:work};}
   case "touch":{const targets=args.filter(a=>!a.startsWith("-"));for(const raw of targets){const p=resolvePath(active.cwd,raw),{parent,name}=getParent(work,p);if(!parent?.children)return{output:`touch: cannot touch '${raw}'`,error:true};if(!parent.children[name])parent.children[name]=file(name,"",user,USERS[user].groups[0]);}return{output:"",nextFs:work};}
   case "cat":{const targets=args.filter(a=>!a.startsWith("-"));if(!targets.length)return{output:stdin};return{output:targets.map(raw=>{const n=getNode(fs,resolvePath(active.cwd,raw));return!n?`cat: ${raw}: No such file or directory`:n.type==="dir"?`cat: ${raw}: Is a directory`:n.content||""}).join("\n")};}
   case "head":case "tail":{const raw=args.find(a=>!a.startsWith("-")),n=raw?getNode(fs,resolvePath(active.cwd,raw)):null;if(!n||n.type!=="file")return{output:`${command}: No such file or directory`,error:true};const ls=(n.content||"").split("\n");return{output:(command==="head"?ls.slice(0,10):ls.slice(-10)).join("\n")};}
   case "less":{const raw=args[0],n=raw?getNode(fs,resolvePath(active.cwd,raw)):null;if(!n||n.type!=="file")return{output:`less: ${raw||"missing file"}: No such file or directory`,error:true};return{output:`--- ${raw} ---\n${n.content||""}\n--- press q to exit ---`};}
   case "grep":{const needle=args.find(a=>!a.startsWith("-"))||"",sourceFile=[...args].reverse().find(a=>!a.startsWith("-")),source=sourceFile&&sourceFile!==needle?(getNode(fs,resolvePath(active.cwd,sourceFile))?.content||""):stdin;return{output:source.split("\n").filter(l=>l.includes(needle)).join("\n")};}
   case "find":{const start=args.find(a=>!a.startsWith("-"))||".",pattern=args[args.indexOf("-name")+1]||"*",base=resolvePath(active.cwd,start),hits:string[]=[];const visit=(p:string,n:FSNode)=>{if(n.name===pattern||(pattern==="*"&&n.name))hits.push(p);if(n.type==="dir")Object.values(n.children||{}).forEach(ch=>visit(resolvePath(p,ch.name),ch));};const n=getNode(fs,base);if(n)visit(base,n);return{output:hits.join("\n")};}
   case "cp":case "mv":{const vals=args.filter(a=>!a.startsWith("-"));if(vals.length<2)return{output:`${command}: missing destination`,error:true};const srcPath=resolvePath(active.cwd,vals[0]),dstPath=resolvePath(active.cwd,vals[1]),src=getNode(work,srcPath),{parent,name}=getParent(work,dstPath);if(!src||!parent?.children)return{output:`${command}: cannot stat '${vals[0]}'`,error:true};parent.children[name]=JSON.parse(JSON.stringify({...src,name}));if(command==="mv"){const sp=getParent(work,srcPath).parent;if(sp?.children)delete sp.children[src.name]}return{output:"",nextFs:work};}
   case "echo":return{output:args.join(" ")}; case "export":{const env={...active.env};args.forEach(pair=>{const [k,...r]=pair.split("=");if(k)env[k]=r.join("=")});return{output:"",nextSession:{env}};} case "env":case "printenv":return{output:Object.entries(active.env).sort().map(([k,v])=>`${k}=${v}`).join("\n")};
   case "alias":{if(!args.length)return{output:Object.entries(active.aliases).map(([k,v])=>`alias ${k}='${v}'`).join("\n")};const raw=args.join(" "),eq=raw.indexOf("=");if(eq<0)return{output:`bash: alias: ${raw}: not found`,error:true};return{output:"",nextSession:{aliases:{...active.aliases,[raw.slice(0,eq)]:raw.slice(eq+1).replace(/^['"]|['"]$/g,"")}}};}
   case "history":return{output:active.history.map((h,i)=>` ${String(i+1).padStart(3)}  ${h}`).join("\n")}; case "clear":return{output:"",nextSession:{lines:[]}};
   case "uname":return{output:args.includes("-a")?"Linux henry 6.8.0-virtual #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux":"Linux"}; case "uptime":return{output:" 17:52:41 up 2:14, 1 user, load average: 0.12, 0.08, 0.03"}; case "free":return{output:"               total        used        free      shared  buff/cache   available\nMem:        16384000     3481600    11821000      132096      1274496    12822144\nSwap:        4194304           0     4194304"}; case "df":return{output:"Filesystem      Size  Used Avail Use% Mounted on\nvirtual-disk    128G   13G  115G  10% /"}; case "du":return{output:"12K\t/etc\n4.0K\t/tmp\n128M\t/usr\n420M\t/home/henry\n620M\t/var"}; case "lsblk":return{output:"NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS\nvda    254:0    0   128G  0 disk\n└─vda1 254:1    0   128G  0 part /"}; case "lscpu":return{output:"Architecture: x86_64\nCPU(s): 8\nModel name: Virtual CPU\nThread(s) per core: 2\nVirtualization: browser"}; case "lspci":return{output:"00:02.0 VGA compatible controller: Virtual Graphics Adapter\n00:03.0 Ethernet controller: Virtual Network Device"}; case "lsusb":return{output:"Bus 001 Device 001: Virtual USB root hub\nBus 001 Device 002: Virtual HID device"};
   case "ps":return{output:["  PID USER     %CPU %MEM COMMAND",...BASE_PROCESSES.map(p=>` ${p[0]} ${p[1].padEnd(8)} ${p[2].padStart(4)} ${p[3].padStart(4)} ${p[4]}`)].join("\n")}; case "top":case "htop":return{output:"Tasks: 24 total, 1 running, 23 sleeping\n%Cpu(s): 2.1 us, 0.9 sy, 97.0 id\nMiB Mem : 16000 total, 3400 used, 11800 free\n\n  PID USER      %CPU %MEM COMMAND\n 1180 user       1.3  2.1 terminal-ui\n 1042 user       0.8  1.4 bash"};
   case "ip":case "ifconfig":return{output:"eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500\n        inet 192.168.1.42  netmask 255.255.255.0\nlo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536\n        inet 127.0.0.1  netmask 255.0.0.0"}; case "ping":return{output:`${args[0]||"localhost"} (${args[0]||"127.0.0.1"}): simulated ICMP in browser sandbox\n64 bytes from ${args[0]||"localhost"}: icmp_seq=1 ttl=57 time=12.4 ms\n64 bytes from ${args[0]||"localhost"}: icmp_seq=2 ttl=57 time=11.8 ms\n--- ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss`}; case "traceroute":case "tracepath":return{output:` 1  192.168.1.1  1.3 ms\n 2  10.0.0.1  5.7 ms\n 3  ${args[0]||"example.com"}  12.9 ms\n(simulated; raw sockets unavailable in browsers)`}; case "dig":case "nslookup":case "host":return{output:`Server: 1.1.1.1\nAddress: 1.1.1.1#53\n\nName: ${args[0]||"example.com"}\nAddress: 93.184.216.34\n(simulated DNS response)`};
   case "curl":case "wget":{const url=args.find(a=>/^https?:\/\//i.test(a));if(!url)return{output:`${command}: try '${command} https://example.com'`,error:true};try{const r=await fetch(url);const text=await r.text();return{output:`${command}: HTTP ${r.status} ${r.statusText}\ncontent-type: ${r.headers.get("content-type")||"unknown"}\n\n${text.slice(0,6000)}`};}catch{return{output:`${command}: network request blocked by browser CORS policy. No server-side request was made.`,error:true}}}
   case "netstat":case "ss":return{output:"Netid State  Local Address:Port  Peer Address:Port Process\ntcp   LISTEN  0.0.0.0:22        0.0.0.0:*     sshd (simulated)\ntcp   ESTAB   192.168.1.42:443  1.1.1.1:*     browser-fetch"}; case "route":return{output:"Destination     Gateway         Genmask         Flags Iface\n0.0.0.0         192.168.1.1     0.0.0.0         UG    eth0\n192.168.1.0     0.0.0.0         255.255.255.0 U     eth0"}; case "which":return{output:args[0]&&COMMANDS.includes(args[0])?`/usr/bin/${args[0]}`:""};
   case "sudo":if(user==="root")return executeSimple(args,stdin);return{output:`[sudo] password for ${user}:`,nextSession:{passwordMode:user,passwordTarget:"root"}}; case "su":{const target=(args.find(a=>!a.startsWith("-"))||"root") as UserName;if(!USERS[target])return{output:`su: user ${target} does not exist`,error:true};return{output:`Password for ${target}:`,nextSession:{passwordMode:user,passwordTarget:target}};}
   case "passwd":return{output:"Changing password for user.\nNew password:\nRetype new password:\npasswd: password updated successfully (simulated)."}; case "chmod":case "chown":if(!priv)return{output:`${command}: permission denied (try sudo)`,error:true};return{output:"",nextFs:work}; case "apt":case "apt-get":case "dpkg":if(!priv)return{output:`${command}: permission denied (try sudo)`,error:true};return{output:command==="apt"&&args[0]==="update"?"Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease\nHit:2 http://security.ubuntu.com/ubuntu noble-security InRelease\nReading package lists... Done\n1842 packages can be upgraded.":`${command}: simulated package operation completed successfully.`};
   case "systemctl":case "service":if(!priv)return{output:`${command}: permission denied (try sudo)`,error:true};return{output:`${command}: simulated system manager: ${args.join(" ")||"status"}\n● nginx.service - Virtual web server\n   Loaded: loaded\n   Active: active (running)`}; case "journalctl":return{output:"Aug 30 17:50 henry systemd[1]: Started NetworkManager.\nAug 30 17:51 henry systemd[1]: Started ssh.service.\nAug 30 17:52 henry bash[1042]: terminal session ready."}; case "shutdown":case "reboot":return priv?{output:`${command}: simulated. No host shutdown is performed.`}:{output:`${command}: permission denied (try sudo)`,error:true}; case "date":return{output:new Date().toString()}; case "timedatectl":return{output:`Local time: ${new Date().toLocaleString()}\nTime zone: Europe/Paris\nSystem clock synchronized: yes\nNTP service: active (simulated)`}; case "kill":case "pkill":return{output:`Terminated simulated process ${args.join(" ")||"<unknown>"}.`}; case "jobs":return{output:"[1]+  Running                 sleep 999 &"}; case "bg":case "fg":return{output:`${command}: simulated job control complete`};
   case "bash":case "sh":return{output:`${command==='bash'?"GNU bash, version 5.2.21":"dash 0.5"}\nEntering nested ${command} shell. Type exit to return.`,nextSession:{shellStack:[...active.shellStack,active.env.SHELL],env:{...active.env,SHELL:command==='bash'?"/bin/bash":"/bin/sh"}}}; case "exit":return active.shellStack.length?{output:"logout",nextSession:{shellStack:active.shellStack.slice(0,-1),env:{...active.env,SHELL:active.shellStack.at(-1)||"/bin/bash"}}}:{output:"logout",stop:true};
   case "tar":case "gzip":case "gunzip":case "zip":case "unzip":return{output:`${command}: archive operation completed in virtual filesystem.`}; case "nano":{const raw=args.find(a=>!a.startsWith("-"));if(!raw)return{output:"nano: missing file operand",error:true};const p=resolvePath(active.cwd,raw),n=getNode(fs,p);if(n?.type==="dir")return{output:`nano: ${raw}: Is a directory`,error:true};return{output:`[ nano ] ${p} — opening editor`,nextSession:{}};}
   default:return{output:`bash: ${command}: command not found`,error:true};
  }
 };

 const executeLine=async()=>{if(!active.input.trim())return;const commandLine=active.input.trim();if(active.passwordMode){const target=active.passwordTarget||"root";if(commandLine!==USERS[target].password){appendOutput("Sorry, try again.","error");updateActive({input:"",passwordMode:null,passwordTarget:null});return}updateActive({input:"",passwordMode:null,passwordTarget:null,user:target,cwd:target==="root"?"/root":USERS[target].home});appendOutput(formatPrompt(target,target==="root"?"/root":USERS[target].home));return}
  const prompt=formatPrompt(active.user,active.cwd);setSessions(c=>c.map(s=>s.id===activeId?{...s,input:"",history:[...s.history,commandLine],historyIndex:-1,lines:[...s.lines,line("input",`${prompt} ${commandLine}`,idRef)]}:s));const tokens=tokenize(commandLine);const segments:string[][]=[[]],connectors:string[]=[];for(const t of tokens){if(["|",";","&&"].includes(t)){connectors.push(t);segments.push([])}else segments.at(-1)!.push(t)}let stdin="",nextFs:FSNode|undefined,sessionPatch:Partial<Session>={};for(let i=0;i<segments.length;i++){let argv=segments[i];if(!argv.length)continue;let redirect:{append:boolean;path:string}|null=null;const filtered:string[]=[];for(let j=0;j<argv.length;j++){if(argv[j]==="||argv[j]===">>")redirect={append:argv[j]===">>",path:argv[++j]||""};else filtered.push(argv[j])}const r=await executeSimple(filtered,stdin);if(r.error){appendOutput(r.output,"error");stdin="";break}stdin=r.output;if(r.nextFs)nextFs=r.nextFs;if(r.nextSession)sessionPatch={...sessionPatch,...r.nextSession};if(redirect){const f=cloneFS(nextFs||fs),p=resolvePath(active.cwd,redirect.path),{parent,name}=getParent(f,p);if(!parent?.children){appendOutput(`bash: ${redirect.path}: No such file or directory`,"error");break}const old=parent.children[name];parent.children[name]=old||file(name,"",active.user,USERS[active.user].groups[0]);parent.children[name].content=redirect.append?(old?.content||"")+stdin:stdin;nextFs=f;stdin=""}if(connectors[i]!=="|"&&stdin){appendOutput(stdin);stdin=""}}
  if(nextFs)persistFS(nextFs);if(Object.keys(sessionPatch).length)updateActive(sessionPatch);if(commandLine==="nano"){const p=resolvePath(active.cwd,""),n=getNode(fs,p);void n}inputRef.current?.focus();
 };
 const onKey=async(e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key==="Enter"){e.preventDefault();await executeLine()}else if(e.key==="ArrowUp"){e.preventDefault();const i=active.historyIndex<0?active.history.length-1:Math.max(0,active.historyIndex-1);if(i>=0)updateActive({historyIndex:i,input:active.history[i]})}else if(e.key==="ArrowDown"){e.preventDefault();const i=active.historyIndex+1;updateActive({historyIndex:i,input:i>=0&&i<active.history.length?active.history[i]:""})}else if(e.key==="Tab"){e.preventDefault();autoComplete()}else if(e.ctrlKey&&e.key.toLowerCase()==="l"){e.preventDefault();updateActive({lines:[]})}else if(e.ctrlKey&&e.key.toLowerCase()==="c"){updateActive({input:""});appendOutput("^C")}};
 const addTab=()=>{const s=getInitialSession();s.title=`terminal-${sessions.length+1}`;s.user=active.user;s.cwd=active.cwd;s.env={...active.env};s.aliases={...active.aliases};setSessions(c=>[...c,s]);setActiveId(s.id)};const closeTab=(id:string)=>{if(sessions.length===1)return;const rest=sessions.filter(s=>s.id!==id);setSessions(rest);if(id===activeId)setActiveId(rest.at(-1)!.id)};
 const toggleFullscreen=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}setFullscreen(v=>!v)};
 const exportFS=()=>{const b=new Blob([JSON.stringify(fs,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="henry-linux-filesystem.json";a.click();URL.revokeObjectURL(u)};const importFS=(f:File)=>{const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result));if(x?.type==="dir"&&x.children)persistFS(x)}catch{appendOutput("import: invalid virtual filesystem file","error")}};r.readAsText(f)};
 const filteredLines=useMemo(()=>searchQuery?active.lines.filter(l=>l.text.toLowerCase().includes(searchQuery.toLowerCase())):active.lines,[active.lines,searchQuery]);
 return <div className="linux-app" onClick={()=>inputRef.current?.focus()}><header className="topbar"><div className="brand"><div className="brand-icon"><SquareTerminal size={18}/></div><div><strong>henry</strong><span>Ubuntu Simulator</span></div></div><div className="top-actions">{[[FolderOpen,"files"],[Activity,"processes"],[Cpu,"system"],[Network,"network"],[Settings,"settings"]].map(([Icon,key])=><button key={String(key)} title={String(key)} onClick={e=>{e.stopPropagation();setPanel(panel===key?null:key as typeof panel)}}><Icon size={16}/></button>)}<button title="Search" onClick={e=>{e.stopPropagation();setSearchOpen(true)}}><Search size={16}/></button><button title="Fullscreen" onClick={e=>{e.stopPropagation();void toggleFullscreen()}}>{fullscreen?<Minimize2 size={16}/>:<Maximize2 size={16}/>}</button></div></header>
 <div className="tabbar" onClick={e=>e.stopPropagation()}>{sessions.map(s=><button key={s.id} className={`tab ${s.id===activeId?"active":""}`} onClick={()=>setActiveId(s.id)}><span className="tab-dot"/>{s.title}{sessions.length>1&&<span className="tab-close" onClick={e=>{e.stopPropagation();closeTab(s.id)}}><X size={12}/></span>}</button>)}<button className="add-tab" onClick={addTab}><Plus size={15}/></button></div>
 <main className="workspace"><section className="terminal-shell"><div className="terminal-titlebar"><div className="window-controls"><span className="wc red"/><span className="wc yellow"/><span className="wc green"/></div><div className="terminal-title"><SquareTerminal size={14}/> {formatPrompt(active.user,active.cwd)}</div><div className="title-spacer"/><span className="status-pill"><Wifi size={12}/> sandbox</span></div><div className="terminal-output" ref={terminalRef}>{filteredLines.map(l=><div key={l.id} className={`terminal-line ${l.kind}`}><span>{l.text}</span></div>)}<div className="input-row"><span className="prompt">{formatPrompt(active.user,active.cwd)} </span><input ref={inputRef} autoFocus value={active.input} onChange={e=>updateActive({input:e.target.value})} onKeyDown={onKey} spellCheck={false} autoComplete="off"/><span className="cursor"/></div></div><div className="terminal-footer"><span><Shield size={12}/> Browser sandbox · no host commands</span><span>Ctrl+L clear · Ctrl+F search · Tab complete · ↑↓ history</span></div></section>
 <AnimatePresence>{panel&&<motion.aside initial={{opacity:0,x:24}} animate={{opacity:1,x:0}} exit={{opacity:0,x:24}} className="side-panel" onClick={e=>e.stopPropagation()}><div className="panel-header"><div><span className="eyebrow">SYSTEM</span><h2>{panel==="files"?"File explorer":panel==="processes"?"Processes":panel==="system"?"System":panel==="network"?"Network":"Settings"}</h2></div><button onClick={()=>setPanel(null)}><X size={16}/></button></div>{panel==="files"&&<FileExplorer root={fs} cwd={active.cwd} onNavigate={p=>updateActive({cwd:p})} onImport={importFS} onExport={exportFS}/>} {panel==="processes"&&<ProcessPanel/>}{panel==="system"&&<SystemPanel user={active.user} cwd={active.cwd}/>} {panel==="network"&&<NetworkPanel/>}{panel==="settings"&&<SettingsPanel sessions={sessions.length} onReset={()=>{persistFS(cloneFS(initialFiles));const s=getInitialSession();setSessions([s]);setActiveId(s.id)}}/>}</motion.aside>}</AnimatePresence></main>
 <AnimatePresence>{searchOpen&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setSearchOpen(false)}><motion.div className="search-modal" initial={{y:-10}} animate={{y:0}} onClick={e=>e.stopPropagation()}><Search size={17}/><input autoFocus placeholder="Search terminal output…" value={searchQuery} onChange={e=>setSearchQuery(e.target.value)}/><span>{filteredLines.length} matches</span><button onClick={()=>setSearchOpen(false)}><X size={15}/></button></motion.div></motion.div>}</AnimatePresence>
 <div className="shortcut-strip"><span><Gauge size={13}/> 16 GiB</span><span><HardDrive size={13}/> 128 GiB</span><span><Server size={13}/> 8 vCPU</span><span><Network size={13}/> 192.168.1.42</span><span className="push-right">{active.user}@henry · {active.cwd}</span></div></div>;
}

function FileExplorer({root,cwd,onNavigate,onImport,onExport}:{root:FSNode;cwd:string;onNavigate:(p:string)=>void;onImport:(f:File)=>void;onExport:()=>void}){const n=getNode(root,cwd)||root,entries=Object.values(n.children||{}).sort((a,b)=>Number(b.type==="dir")-Number(a.type==="dir")||a.name.localeCompare(b.name));return <div className="panel-body"><div className="path-box"><span>/</span><input value={cwd} onChange={e=>onNavigate(resolvePath("/",e.target.value))}/></div><div className="explorer-list">{cwd!=="/"&&<button onClick={()=>onNavigate(resolvePath(cwd,".."))}><ChevronRight size={14}/> ..</button>}{entries.map(x=><button key={x.name} onDoubleClick={()=>x.type==="dir"&&onNavigate(resolvePath(cwd,x.name))}><span className="file-icon">{x.type==="dir"?<Folder size={14}/>:<FileText size={14}/>}</span>{x.name}<span className="file-type">{x.type}</span></button>)}</div><div className="panel-actions"><button onClick={onExport}><Download size={14}/> Export FS</button><label><Upload size={14}/> Import FS<input type="file" accept="application/json" hidden onChange={e=>e.target.files?.[0]&&onImport(e.target.files[0])}/></label></div></div>}
function ProcessPanel(){return <div className="panel-body"><div className="metric-grid"><div><strong>24</strong><span>tasks</span></div><div><strong>2.1%</strong><span>cpu</span></div><div><strong>3.4G</strong><span>memory</span></div></div><div className="table-wrap"><table><thead><tr><th>PID</th><th>USER</th><th>%CPU</th><th>COMMAND</th></tr></thead><tbody>{BASE_PROCESSES.map(p=><tr key={p[0]}><td>{p[0]}</td><td>{p[1]}</td><td>{p[2]}</td><td>{p[4]}</td></tr>)}</tbody></table></div></div>}
function SystemPanel({user,cwd}:{user:UserName;cwd:string}){return <div className="panel-body"><div className="info-card"><Cpu size={18}/><div><span>CPU</span><strong>Virtual CPU · 8 cores</strong></div></div><div className="info-card"><Layers3 size={18}/><div><span>Kernel</span><strong>Linux 6.8.0-virtual</strong></div></div><div className="info-card"><Shield size={18}/><div><span>Session</span><strong>{user}@henry · {cwd}</strong></div></div><div className="info-card"><BookOpen size={18}/><div><span>Shell</span><strong>{user==="root"?"root shell":"bash 5.2"}</strong></div></div></div>}
function NetworkPanel(){return <div className="panel-body"><div className="online-banner"><span className="pulse"/> Browser network bridge available</div><div className="net-card"><div><Network size={15}/><strong>eth0</strong><span>UP</span></div><p>192.168.1.42 / 24</p><small>Gateway 192.168.1.1 · DNS 1.1.1.1</small></div><div className="net-card"><div><Wifi size={15}/><strong>HTTP</strong><span>Fetch</span></div><p>Real requests when CORS permits</p><small>Raw ICMP/TCP sockets remain simulated.</small></div></div>}
function SettingsPanel({sessions,onReset}:{sessions:number;onReset:()=>void}){return <div className="panel-body"><div className="settings-row"><div><strong>Tabs</strong><span>{sessions} terminal session(s)</span></div><SquareTerminal size={16}/></div><div className="settings-row"><div><strong>Persistence</strong><span>Local browser storage enabled</span></div><RefreshCw size={16}/></div><div className="settings-row"><div><strong>Host safety</strong><span>System command execution disabled</span></div><Shield size={16}/></div><button className="danger-button" onClick={onReset}><Trash2 size={14}/> Reset virtual filesystem</button></div>}
