import { useEffect, useMemo, useRef, useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Activity, ChevronRight, Cpu, Download, FileText, Folder, FolderOpen, Gauge, HardDrive, Maximize2, Minimize2, Network, Plus, Search, Server, Settings, Shield, SquareTerminal, Trash2, Upload, Wifi, X } from "lucide-react";

type UserName = "guest" | "user" | "admin" | "root";
type Node = { type: "dir" | "file"; name: string; mode: string; owner: string; group: string; content?: string; children?: Record<string, Node> };
type Line = { id: number; kind: "input" | "output" | "error" | "system"; text: string };
type Session = { id: string; title: string; user: UserName; cwd: string; input: string; history: string[]; historyIndex: number; env: Record<string,string>; aliases: Record<string,string>; lines: Line[]; shellStack: string[]; loginStack: Array<{user:UserName;cwd:string}>; passwordPrompt: null | { target: UserName; pending?: string } };

const USERS: Record<UserName,{uid:number;gid:number;groups:string[];home:string;shell:string;password:string}> = {
  guest:{uid:1001,gid:1001,groups:["guest"],home:"/home/guest",shell:"/bin/bash",password:"guest"},
  user:{uid:1000,gid:1000,groups:["users","sudo"],home:"/home/henry",shell:"/bin/bash",password:"henry"},
  admin:{uid:900,gid:900,groups:["admin","sudo","users"],home:"/home/admin",shell:"/bin/bash",password:"admin"},
  root:{uid:0,gid:0,groups:["root","sudo","admin"],home:"/root",shell:"/bin/bash",password:"root"},
};
const COMMANDS = ["alias","apt","apt-get","awk","bash","bg","banner","cat","cd","chmod","chown","clear","cp","curl","date","df","dig","dpkg","du","echo","env","exit","export","fastfetch","fg","find","free","grep","groups","gunzip","head","help","history","hostname","htop","id","ifconfig","ip","jobs","kill","less","ls","lsblk","lscpu","lspci","lsusb","matrix","mkdir","motd","mv","nano","neofetch","netstat","network","nslookup","passwd","ping","pkill","printenv","ps","pwd","reboot","rm","rmdir","route","service","shutdown","ss","su","sudo","sysinfo","systemctl","tail","tar","timedatectl","top","touch","tracepath","traceroute","uname","unzip","uptime","users","wget","whoami","which","zip"];
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
const dir=(name:string,owner="root",group="root",children:Record<string,Node>={}):Node=>({type:"dir",name,mode:"drwxr-xr-x",owner,group,children});
const file=(name:string,content="",owner="root",group="root",mode="-rw-r--r--"):Node=>({type:"file",name,content,owner,group,mode});
const INITIAL:Node=dir("/","root","root",{
  bin:dir("bin","root","root",{bash:file("bash","ELF 64-bit virtual bash binary","root","root","-rwxr-xr-x"),sh:file("sh","ELF 64-bit virtual sh binary","root","root","-rwxr-xr-x")}),
  boot:dir("boot","root","root",{"vmlinuz-6.8.0":file("vmlinuz-6.8.0","Ubuntu virtual kernel 6.8.0")}),
  dev:dir("dev"),etc:dir("etc","root","root",{hostname:file("hostname","henry\n"),"os-release":file("os-release","PRETTY_NAME=\"Ubuntu Simulator\"\nVERSION=\"24.04 LTS\"\n"),hosts:file("hosts","127.0.0.1 localhost\n127.0.1.1 henry\n")}),
  home:dir("home","root","root",{henry:dir("henry","user","users",{Desktop:dir("Desktop","user","users"),Documents:dir("Documents","user","users",{"welcome.txt":file("welcome.txt","Welcome to henry's Ubuntu simulator.\n","user","users")}),Downloads:dir("Downloads","user","users"),Pictures:dir("Pictures","user","users"),Videos:dir("Videos","user","users")}),guest:dir("guest","guest","guest"),admin:dir("admin","admin","admin")}),
  lib:dir("lib"),media:dir("media"),mnt:dir("mnt"),opt:dir("opt"),proc:dir("proc"),root:dir("root","root","root",{".bashrc":file(".bashrc","# root shell configuration\n","root","root","-rw-------")}),run:dir("run"),sbin:dir("sbin"),srv:dir("srv"),sys:dir("sys"),tmp:dir("tmp","root","root"),
  usr:dir("usr","root","root",{bin:dir("bin"),local:dir("local"),share:dir("share")}),var:dir("var","root","root",{log:dir("log","root","root",{syslog:file("syslog","Aug 30 17:50 henry systemd[1]: Starting simulated services...\n","root","adm","-rw-r-----")}),www:dir("www")})
});
function resolvePath(cwd:string,target="."){const raw=target.startsWith("/")?target:`${cwd}/${target}`;const out:string[]=[];for(const p of raw.split("/")){if(!p||p===".")continue;if(p==="..")out.pop();else out.push(p)}return "/"+out.join("/");}
function getNode(root:Node,path:string):Node|null{if(path==="/")return root;let n=root;for(const part of path.split("/").filter(Boolean)){if(n.type!=="dir"||!n.children?.[part])return null;n=n.children[part]}return n;}
function getParent(root:Node,path:string){const p=resolvePath("/",path),parts=p.split("/").filter(Boolean),name=parts.pop()||"",parentPath="/"+parts.join("/");return {parent:getNode(root,parentPath||"/"),name,parentPath:parentPath||"/"};}
function prompt(s:Session){const display=s.user==="root"?(s.cwd==="/root"||s.cwd==="/"?"~":s.cwd):(s.cwd===USERS[s.user].home?"~":s.cwd);return `${s.user}@henry:${display}${s.user==="root"?"#":"$"}`;}
function tokenize(input:string){const out:string[]=[];let cur="",q:"'"|'"'|null=null;for(let i=0;i<input.length;i++){const c=input[i];if(c==="\\"&&i+1<input.length){cur+=input[++i];continue}if(q){if(c===q)q=null;else cur+=c;continue}if(c==="'"||c==='"'){q=c;continue}if(/\s/.test(c)){if(cur){out.push(cur);cur=""}continue}if(c==='|'||c===';'||c==='>'){if(cur){out.push(cur);cur=""}if(c==='>'&&input[i+1]==='>'){out.push('>>');i++}else out.push(c);continue}if(c==='&'&&input[i+1]==='&'){if(cur){out.push(cur);cur=""}out.push('&&');i++;continue}cur+=c}if(cur)out.push(cur);return out;}
function expand(v:string,s:Session){return v.replace(/\$(\w+|\{[^}]+\})/g,(_,raw)=>{const k=raw.startsWith("{")?raw.slice(1,-1):raw;if(k==="HOME")return USERS[s.user].home;if(k==="USER")return s.user;if(k==="PWD")return s.cwd;if(k==="SHELL")return s.env.SHELL;return s.env[k]??""});}
function savedFS(){try{const raw=localStorage.getItem("henry-linux-fs");return raw?JSON.parse(raw):clone(INITIAL)}catch{return clone(INITIAL)}}
function initialSession():Session{return{id:crypto.randomUUID(),title:"henry",user:"user",cwd:"/",input:"",history:[],historyIndex:-1,env:{LANG:"en_US.UTF-8",SHELL:"/bin/bash",TERM:"xterm-256color",EDITOR:"nano",PATH:"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"},aliases:{},lines:[{id:1,kind:"system",text:"Ubuntu Simulator 24.04 LTS · Linux 6.8.0-virtual · bash 5.2"},{id:2,kind:"system",text:"Safe browser sandbox: no real host commands are executed."},{id:3,kind:"system",text:"Try: neofetch · ls -la · sudo apt update · curl https://api.github.com"}],shellStack:[],loginStack:[],passwordPrompt:null};}
const PROC=["1 root  0.0 0.1 systemd --system","412 root 0.1 0.4 systemd-journald","621 root 0.0 0.2 NetworkManager","731 root 0.2 0.7 sshd","1042 user 1.3 2.1 bash","1180 user 0.5 1.0 terminal-ui"];

export default function App(){
  const [fs,setFs]=useState<Node>(()=>savedFS());
  const [sessions,setSessions]=useState<Session[]>(()=>[initialSession()]);
  const [activeId,setActiveId]=useState("");
  const [panel,setPanel]=useState<"files"|"processes"|"system"|"network"|"settings"|null>(null);
  const [search,setSearch]=useState(""); const [searchOpen,setSearchOpen]=useState(false); const [full,setFull]=useState(false); const [editor,setEditor]=useState<{path:string;content:string}|null>(null);
  const terminalRef=useRef<HTMLDivElement>(null); const inputRef=useRef<HTMLInputElement>(null); const nextId=useRef(10);
  useEffect(()=>{if(!activeId&&sessions[0])setActiveId(sessions[0].id)},[activeId,sessions]);
  const active=sessions.find(s=>s.id===activeId)??sessions[0];
  const update=(patch:Partial<Session>)=>setSessions(xs=>xs.map(s=>s.id===active.id?{...s,...patch}:s));
  const emit=(text:string,kind:Line["kind"]="output")=>update({lines:[...active.lines,...text.split("\n").map(t=>({id:nextId.current++,kind,text:t}))]});
  useEffect(()=>{terminalRef.current?.scrollTo({top:terminalRef.current.scrollHeight})},[active.lines.length]);
  const persist=(n:Node)=>{setFs(n);try{localStorage.setItem("henry-linux-fs",JSON.stringify(n))}catch{}};
  const requireRoot=(cmd:string)=>active.user==="root"?null:`${cmd}: Permission denied`;

  const cmd=async(argv:string[],stdin=""):Promise<{out:string;ok?:boolean;fs?:Node;session?:Partial<Session>}>=>{
    if(!argv[0])return{out:""}; const c=expand(argv[0],active); const args=argv.slice(1).map(a=>expand(a,active)); const work=clone(fs); const user=active.user;
    if(active.aliases[c]){const a=[...tokenize(active.aliases[c]),...args];return cmd(a,stdin)}
    const out=(s:string,ok=true)=>({out:s,ok});
    switch(c){
      case "help":return out("File: ls cd pwd mkdir rmdir touch cat less head tail cp mv rm find grep nano clear history\nShell: bash sh sudo su exit echo export env printenv alias\nSystem: uname hostname uptime free df du lsblk lscpu lspci lsusb ps top htop\nNetwork: ip ifconfig ping traceroute tracepath curl wget dig nslookup host netstat ss route\nPackages: apt apt-get dpkg · Services: systemctl service journalctl · Users: whoami id users groups passwd chmod chown\nJobs: kill pkill jobs bg fg · Special: neofetch fastfetch matrix banner motd sysinfo network about");
      case "about":return out("henry Linux Terminal — browser-only Ubuntu simulator. The filesystem, users and processes are virtual; the host computer is never controlled.");
      case "motd":return out("Welcome to Ubuntu Simulator 24.04 LTS.\nLast login: today on tty1\n\nThis shell is safe and runs entirely inside your browser.");
      case "banner":return out("██╗  ██╗███████╗███╗   ██╗██████╗ ██╗   ██╗\n██║  ██║██╔════╝████╗  ██║██╔══██╗╚██╗ ██╔╝\n███████║█████╗  ██╔██╗ ██║██████╔╝ ╚████╔╝\n██╔══██║██╔══╝  ██║╚██╗██║██╔═══╝   ╚██╔╝\n██║  ██║███████╗██║ ╚████║██║        ██║\n╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝        ╚═╝");
      case "matrix":return out(["1 0 1 1 0 0 1 0 1 1","0 1 0 0 1 1 0 1 0 1","1 1 0 1 0 1 1 0 0 1","0 0 1 1 1 0 1 1 0 0"].join("\n"));
      case "neofetch":case "fastfetch":return out(`user@henry                     Ubuntu Simulator 24.04 LTS\n-------------------            --------------------------\nOS: Ubuntu Simulator x86_64\nHost: Browser Virtual Machine\nKernel: 6.8.0-virtual\nShell: ${active.env.SHELL.split("/").pop()}\nTerminal: xterm-256color\nCPU: Virtual CPU (8 cores)\nMemory: 16 GiB\nDisk: 128 GiB virtual disk\nUptime: 02:14:37\nPackages: 1842 (apt)\nResolution: ${window.innerWidth}x${window.innerHeight}\nNetwork: 192.168.1.42`);
      case "sysinfo":return out(`Hostname: henry\nOS: Ubuntu Simulator 24.04 LTS\nKernel: 6.8.0-virtual\nArchitecture: x86_64\nCPU: 8 vCPU\nRAM: 16 GiB\nStorage: 128 GiB\nShell: ${active.env.SHELL}`);
      case "whoami":return out(user);case "groups":return out(USERS[user].groups.join(" "));case "users":return out("guest user admin root");
      case "id":return out(`uid=${USERS[user].uid}(${user}) gid=${USERS[user].gid}(${user}) groups=${USERS[user].groups.map(g=>`${USERS[user].gid}(${g})`).join(",")}`);
      case "hostname":return out("henry");case "pwd":return out(active.cwd);
      case "cd":{const target=args[0]??"~";const p=target==="~"?USERS[user].home:resolvePath(active.cwd,target);const n=getNode(fs,p);return n?.type==="dir"?{out:"",session:{cwd:p}}:out(`bash: cd: ${target}: No such file or directory`,false)}
      case "ls":{const all=args.some(a=>a.includes("a"));const long=args.some(a=>a.includes("l"));const target=args.find(a=>!a.startsWith("-"))??active.cwd;const p=target==="~"?USERS[user].home:resolvePath(active.cwd,target);const n=getNode(fs,p);if(!n)return out(`ls: cannot access '${target}': No such file or directory`,false);if(n.type==="file")return out(n.name);const list=Object.values(n.children??{}).filter(x=>all||!x.name.startsWith("."));return out(long?list.map(x=>`${x.mode} 1 ${x.owner.padEnd(6)} ${x.group.padEnd(6)} ${String(x.content?.length??0).padStart(5)} Aug 30 17:50 ${x.name}${x.type==="dir"?"/":""}`).join("\n"):list.map(x=>x.name+(x.type==="dir"?"/":"")).join("  "));}
      case "mkdir":{const names=args.filter(a=>!a.startsWith("-"));if(!names.length)return out("mkdir: missing operand",false);for(const name of names){const {parent,n}=(()=>{const p=resolvePath(active.cwd,name);const q=getParent(work,p);return{parent:q.parent,n:q.name}})();if(!parent?.children)return out(`mkdir: cannot create directory '${name}'`,false);parent.children[n]={type:"dir",name:n,mode:"drwxr-xr-x",owner:user,group:USERS[user].groups[0],children:{}};}return{out:"",fs:work};}
      case "touch":{for(const name of args){const p=resolvePath(active.cwd,name),q=getParent(work,p);if(!q.parent?.children)return out(`touch: cannot touch '${name}'`,false);if(!q.parent.children[q.name])q.parent.children[q.name]=file(q.name,"",user,USERS[user].groups[0]);}return{out:"",fs:work};}
      case "cat":case "less":{const name=args[0];if(!name)return out(stdin);const n=getNode(fs,resolvePath(active.cwd,name));if(!n)return out(`${c}: ${name}: No such file or directory`,false);if(n.type==="dir")return out(`${c}: ${name}: Is a directory`,false);return out(n.content??"");}
      case "head":case "tail":{const name=args.find(a=>!a.startsWith("-"));const n=name?getNode(fs,resolvePath(active.cwd,name)):null;if(!n||n.type!=="file")return out(`${c}: No such file or directory`,false);const ls=(n.content??"").split("\n");return out((c==="head"?ls.slice(0,10):ls.slice(-10)).join("\n"));}
      case "grep":{const vals=args.filter(a=>!a.startsWith("-")),needle=vals[0]??"",fileArg=vals[1];let source=stdin;if(fileArg){const n=getNode(fs,resolvePath(active.cwd,fileArg));source=n?.type==="file"?n.content??"":""}return out(source.split("\n").filter(l=>l.includes(needle)).join("\n"));}
      case "find":{const start=args[0]&&!args[0].startsWith("-")?args[0]:".";const pattern=args.includes("-name")?args[args.indexOf("-name")+1]:"*";const base=resolvePath(active.cwd,start),hits:string[]=[];const walk=(p:string,n:Node)=>{if(pattern==="*"||n.name===pattern)hits.push(p);if(n.type==="dir")Object.values(n.children??{}).forEach(ch=>walk(resolvePath(p,ch.name),ch));};const n=getNode(fs,base);if(n)walk(base,n);return out(hits.join("\n"));}
      case "cp":case "mv":{const vals=args.filter(a=>!a.startsWith("-"));if(vals.length<2)return out(`${c}: missing operand`,false);const src=getNode(work,resolvePath(active.cwd,vals[0]));const dest=getParent(work,resolvePath(active.cwd,vals[1]));if(!src||!dest.parent?.children)return out(`${c}: cannot stat '${vals[0]}'`,false);dest.parent.children[dest.name]=clone({...src,name:dest.name});if(c==="mv"){const q=getParent(work,resolvePath(active.cwd,vals[0]));if(q.parent?.children)delete q.parent.children[q.name]}return{out:"",fs:work};}
      case "rm":case "rmdir":{const recursive=args.some(a=>a.includes("r")),vals=args.filter(a=>!a.startsWith("-"));if(!vals.length)return out(`${c}: missing operand`,false);for(const v of vals){const q=getParent(work,resolvePath(active.cwd,v));const n=getNode(work,resolvePath(active.cwd,v));if(!n||!q.parent?.children)return out(`${c}: cannot remove '${v}': No such file or directory`,false);if(c==="rmdir"&&n.type==="dir"&&Object.keys(n.children??{}).length)return out(`rmdir: failed to remove '${v}': Directory not empty`,false);if(n.type==="dir"&&!recursive)return out(`rm: cannot remove '${v}': Is a directory`,false);delete q.parent.children[q.name];}return{out:"",fs:work};}
      case "echo":return out(args.join(" "));
      case "export":{const env={...active.env};for(const a of args){const i=a.indexOf("=");if(i>0)env[a.slice(0,i)]=a.slice(i+1)}return{out:"",session:{env}};}
      case "env":case "printenv":return out(Object.entries(active.env).sort().map(([k,v])=>`${k}=${v}`).join("\n"));
      case "alias":{if(!args.length)return out(Object.entries(active.aliases).map(([k,v])=>`alias ${k}='${v}'`).join("\n"));const raw=args.join(" "),i=raw.indexOf("=");if(i<1)return out("bash: alias: invalid syntax",false);return{out:"",session:{aliases:{...active.aliases,[raw.slice(0,i)]:raw.slice(i+1)}}};}
      case "history":return out(active.history.map((h,i)=>`${String(i+1).padStart(4)}  ${h}`).join("\n"));case "clear":return{out:"",session:{lines:[]}};
      case "uname":return out(args.includes("-a")?"Linux henry 6.8.0-virtual #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux":"Linux");case "uptime":return out(" 17:52:41 up 2:14, 1 user, load average: 0.12, 0.08, 0.03");case "free":return out("               total        used        free\nMem:        16384000     3481600    11821000\nSwap:        4194304           0     4194304");case "df":return out("Filesystem      Size  Used Avail Use% Mounted on\nvirtual-disk    128G   13G  115G  10% /");case "du":return out("12K /etc\n4.0K /tmp\n128M /usr\n420M /home/henry\n620M /var");case "lsblk":return out("NAME   SIZE TYPE MOUNTPOINT\nvda    128G disk\n└─vda1 128G part /");case "lscpu":return out("Architecture: x86_64\nCPU(s): 8\nModel name: Virtual CPU\nThread(s) per core: 2\nCore(s) per socket: 4");case "lspci":return out("00:02.0 VGA compatible controller: Virtual Graphics Adapter\n00:03.0 Ethernet controller: Virtual Network Device");case "lsusb":return out("Bus 001 Device 001: Virtual USB root hub");case "ps":return out("  PID USER  %CPU %MEM COMMAND\n"+PROC.map(p=>p).join("\n"));case "top":case "htop":return out("Tasks: 24 total, 1 running, 23 sleeping\n%Cpu(s): 2.1 us, 0.9 sy, 97.0 id\nMiB Mem : 16000 total, 3400 used, 11800 free\n\nPID USER COMMAND\n1180 user terminal-ui\n1042 user bash");
      case "ip":case "ifconfig":return out("eth0: UP mtu 1500\n    inet 192.168.1.42  netmask 255.255.255.0\nlo: UP LOOPBACK\n    inet 127.0.0.1");case "ping":return out(`${args[0]??"localhost"} (${args[0]??"127.0.0.1"})\n64 bytes from ${args[0]??"localhost"}: icmp_seq=1 ttl=57 time=12.4 ms\n64 bytes from ${args[0]??"localhost"}: icmp_seq=2 ttl=57 time=11.8 ms\n2 packets transmitted, 2 received, 0% packet loss\n(simulated: browser cannot issue raw ICMP)`);case "traceroute":case "tracepath":return out("1  192.168.1.1  1.3 ms\n2  10.0.0.1  5.7 ms\n3  target 12.9 ms\n(simulated route)");case "dig":case "nslookup":case "host":return out(`Server: 1.1.1.1\nName: ${args[0]??"example.com"}\nAddress: 93.184.216.34\n(simulated DNS response)`);case "netstat":case "ss":return out("tcp LISTEN 0.0.0.0:22 sshd (simulated)\ntcp ESTAB  192.168.1.42:443 browser-fetch");case "route":return out("default via 192.168.1.1 dev eth0\n192.168.1.0/24 dev eth0");
      case "curl":case "wget":{const url=args.find(a=>/^https?:\/\//i.test(a));if(!url)return out(`${c}: URL required`,false);try{const r=await fetch(url);const text=await r.text();return out(`${c}: HTTP ${r.status} ${r.statusText}\ncontent-type: ${r.headers.get("content-type")??"unknown"}\n\n${text.slice(0,7000)}`)}catch{return out(`${c}: blocked by browser CORS/network policy. No backend request was made.`,false)}}
      case "which":return out(COMMANDS.includes(args[0]??"")?`/usr/bin/${args[0]}`:"");case "date":return out(new Date().toString());case "timedatectl":return out(`Local time: ${new Date().toLocaleString()}\nTime zone: Europe/Paris\nNTP service: active (simulated)`);
      case "apt":case "apt-get":case "dpkg":case "systemctl":case "service":case "shutdown":case "reboot":case "chmod":case "chown":{const deny=requireRoot(c);if(deny)return out(deny,false);if(c==="apt"&&args[0]==="update")return out("Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease\nHit:2 http://security.ubuntu.com/ubuntu noble-security InRelease\nReading package lists... Done\n1842 packages can be upgraded.");if(c==="systemctl"||c==="service")return out(`${c}: simulated service manager\n● ssh.service - OpenBSD Secure Shell server\n   Active: active (running)`);return out(`${c}: simulated operation completed successfully.`);}
      case "passwd":return out("Changing password for user.\nNew password:\nRetype new password:\npasswd: password updated successfully (simulated).");case "kill":case "pkill":return out(`Terminated simulated process ${args.join(" ")||"unknown"}.`);case "jobs":return out("[1]+  Running                 sleep 999 &");case "bg":case "fg":return out(`${c}: simulated job control completed`);
      case "sudo":case "su":{const target=(c==="sudo"?(args[0]==="-u"?args[1]:"root"):(args[0]??"root")) as UserName;if(!USERS[target])return out(`${c}: unknown user ${target}`,false);return{out:`Password for ${target}:`,session:{passwordPrompt:{target,pending:c==="sudo"?args.filter(a=>a!=="-u"&&a!==target).join(" ")||undefined:undefined}}};}
      case "bash":case "sh":return{out:`${c === "bash"?"GNU bash, version 5.2.21":"dash 0.5"}\nEntering nested ${c} shell. Type exit to return.`,session:{shellStack:[...active.shellStack,active.env.SHELL],env:{...active.env,SHELL:c==="bash"?"/bin/bash":"/bin/sh"}}};
      case "exit":if(active.shellStack.length)return{out:"logout",session:{shellStack:active.shellStack.slice(0,-1),env:{...active.env,SHELL:active.shellStack.at(-1)??"/bin/bash"}}};if(active.loginStack.length){const back=active.loginStack.at(-1)!;return{out:"logout",session:{user:back.user,cwd:back.cwd,loginStack:active.loginStack.slice(0,-1)}}}return out("logout");
      default:return out(`bash: ${c}: command not found`,false);
    }
  };

  const run=async()=>{const raw=active.input.trim();if(!raw)return;
    if(active.passwordPrompt){const expected=USERS[active.passwordPrompt.target].password;if(raw!==expected){emit("Sorry, try again.","error");update({input:"",passwordPrompt:null});return;}const target=active.passwordPrompt.target;const stack=[...active.loginStack,{user:active.user,cwd:active.cwd}];update({input:"",passwordPrompt:null,user:target,cwd:target==="root"?"/root":USERS[target].home,loginStack:stack});return;}
    update({input:"",history:[...active.history,raw],historyIndex:-1});emit(`${prompt(active)} ${raw}`,"input");
    const t=tokenize(raw);const segments:string[][]=[[]];const ops:string[]=[];for(const x of t){if(x==='|'||x===';'||x==='&&'){ops.push(x);segments.push([])}else segments.at(-1)!.push(x)}
    let stdin="";for(let i=0;i<segments.length;i++){let seg=[...segments[i]];let redirect:{type: string;path:string}|null=null;for(let j=0;j<seg.length;j++){if(seg[j]==='>'||seg[j]==='>>'){redirect={type:seg[j],path:seg[j+1]??""};seg.splice(j,2);break;}}
      const r=await cmd(seg,stdin);if(r.session){update(r.session);if(r.session.lines){} }if(r.fs)persist(r.fs);if(r.out){if(ops[i]==='|')stdin=r.out;else{emit(r.out,r.ok===false?"error":"output");stdin=""}}if(redirect&&r.out){const n=clone(fs),q=getParent(n,resolvePath(active.cwd,redirect.path));if(q.parent?.children){const existing=q.parent.children[q.name];q.parent.children[q.name]=existing??file(q.name,"",active.user,USERS[active.user].groups[0]);q.parent.children[q.name].content=redirect.type==='>>'?(existing?.content??"")+r.out:r.out;persist(n);}}if(ops[i]==='&&'&&r.ok===false)break;}
    inputRef.current?.focus();
  };
  const onKey=async(e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key==="Enter"){e.preventDefault();await run()}else if(e.key==="ArrowUp"){e.preventDefault();if(active.history.length){const idx=active.historyIndex<0?active.history.length-1:Math.max(0,active.historyIndex-1);update({historyIndex:idx,input:active.history[idx]})}}else if(e.key==="ArrowDown"){e.preventDefault();const idx=active.historyIndex+1;update({historyIndex:idx,input:idx>=0&&idx<active.history.length?active.history[idx]:""})}else if(e.key==="Tab"){e.preventDefault();const raw=active.input,last=raw.split(/\s+/).pop()??"";const m=COMMANDS.filter(c=>c.startsWith(last));if(m.length===1&&!raw.includes(" "))update({input:raw.slice(0,-last.length)+m[0]+" "});else if(m.length>1&&!raw.includes(" "))emit(m.join("  "))}else if(e.ctrlKey&&e.key.toLowerCase()==="l"){e.preventDefault();update({lines:[]})}else if(e.ctrlKey&&e.key.toLowerCase()==="c"){e.preventDefault();update({input:""});emit("^C")}};
  const addTab=()=>{const s=initialSession();s.title=`terminal-${sessions.length+1}`;s.user=active.user;s.cwd=active.cwd;s.env={...active.env};s.aliases={...active.aliases};setSessions(xs=>[...xs,s]);setActiveId(s.id)};
  const closeTab=(id:string)=>{if(sessions.length===1)return;const left=sessions.filter(s=>s.id!==id);setSessions(left);if(id===active.id)setActiveId(left[0].id)};
  const toggleFull=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}setFull(v=>!v)};
  const filtered=useMemo(()=>{const q=search.toLowerCase();return q?active.lines.filter(l=>l.text.toLowerCase().includes(q)):active.lines},[active.lines,search]);
  const exportFs=()=>{const b=new Blob([JSON.stringify(fs,null,2)],{type:"application/json"});const u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="henry-linux-filesystem.json";a.click();URL.revokeObjectURL(u)};
  const importFs=(f:File)=>{const r=new FileReader();r.onload=()=>{try{const n=JSON.parse(String(r.result));if(n?.type==="dir")persist(n)}catch{emit("import: invalid filesystem JSON","error")}};r.readAsText(f)};

  return <div className="linux-app" onClick={()=>inputRef.current?.focus()}>
    <header className="topbar"><div className="brand"><div className="brand-icon"><SquareTerminal size={18}/></div><div><strong>henry</strong><span>Ubuntu Simulator</span></div></div><div className="top-actions"><button title="Files" onClick={e=>{e.stopPropagation();setPanel(panel==="files"?null:"files")}}><FolderOpen size={16}/></button><button title="Processes" onClick={e=>{e.stopPropagation();setPanel(panel==="processes"?null:"processes")}}><Activity size={16}/></button><button title="System" onClick={e=>{e.stopPropagation();setPanel(panel==="system"?null:"system")}}><Cpu size={16}/></button><button title="Network" onClick={e=>{e.stopPropagation();setPanel(panel==="network"?null:"network")}}><Network size={16}/></button><button title="Settings" onClick={e=>{e.stopPropagation();setPanel(panel==="settings"?null:"settings")}}><Settings size={16}/></button><button title="Search Ctrl+F" onClick={e=>{e.stopPropagation();setSearchOpen(true)}}><Search size={16}/></button><button title="Fullscreen" onClick={e=>{e.stopPropagation();void toggleFull()}}>{full?<Minimize2 size={16}/>:<Maximize2 size={16}/>}</button></div></header>
    <div className="tabbar" onClick={e=>e.stopPropagation()}>{sessions.map(s=><button key={s.id} className={`tab ${s.id===active.id?"active":""}`} onClick={()=>setActiveId(s.id)}><span className="tab-dot"/>{s.title}{sessions.length>1&&<span className="tab-close" onClick={e=>{e.stopPropagation();closeTab(s.id)}}><X size={12}/></span>}</button>)}<button className="add-tab" onClick={addTab}><Plus size={15}/></button></div>
    <main className="workspace"><section className="terminal-shell"><div className="terminal-titlebar"><div className="window-controls"><span className="wc red"/><span className="wc yellow"/><span className="wc green"/></div><div className="terminal-title"><SquareTerminal size={14}/>{prompt(active)}</div><div className="title-spacer"/><span className="status-pill"><Wifi size={12}/> sandbox</span></div><div className="terminal-output" ref={terminalRef}>{filtered.map(l=><div key={l.id} className={`terminal-line ${l.kind}`}>{l.text}</div>)}<div className="input-row"><span className="prompt">{prompt(active)} </span><input ref={inputRef} value={active.input} onChange={e=>update({input:e.target.value})} onKeyDown={e=>void onKey(e)} spellCheck={false} autoComplete="off" autoFocus/><span className="cursor"/></div></div><div className="terminal-footer"><span><Shield size={12}/> Browser sandbox · no host commands</span><span>Ctrl+L clear · Ctrl+F search · Tab complete · ↑↓ history</span></div></section>
      <AnimatePresence>{panel&&<motion.aside className="side-panel" initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:20}} onClick={e=>e.stopPropagation()}><div className="panel-header"><div><span className="eyebrow">SYSTEM</span><h2>{panel}</h2></div><button onClick={()=>setPanel(null)}><X size={16}/></button></div>{panel==="files"&&<div className="panel-body"><div className="path-box"><span>/</span><input value={active.cwd} onChange={e=>update({cwd:resolvePath("/",e.target.value)})}/></div><div className="explorer-list">{Object.values(getNode(fs,active.cwd)?.children??{}).map(n=><button key={n.name} onDoubleClick={()=>n.type==="dir"&&update({cwd:resolvePath(active.cwd,n.name)})}><span className="file-icon">{n.type==="dir"?<Folder size={14}/>:<FileText size={14}/>}</span>{n.name}<span className="file-type">{n.type}</span></button>)}</div><div className="panel-actions"><button onClick={exportFs}><Download size={14}/>Export</button><label><Upload size={14}/>Import<input hidden type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&importFs(e.target.files[0])}/></label></div></div>}{panel==="processes"&&<div className="panel-body"><div className="metric-grid"><div><strong>24</strong><span>tasks</span></div><div><strong>2.1%</strong><span>cpu</span></div><div><strong>3.4G</strong><span>memory</span></div></div><pre className="panel-pre">{PROC.join("\n")}</pre></div>}{panel==="system"&&<div className="panel-body"><div className="info-card"><Cpu size={18}/><div><span>CPU</span><strong>Virtual CPU · 8 cores</strong></div></div><div className="info-card"><HardDrive size={18}/><div><span>Disk</span><strong>128 GiB virtual disk</strong></div></div><div className="info-card"><Shield size={18}/><div><span>Session</span><strong>{active.user}@henry · {active.cwd}</strong></div></div><div className="info-card"><Gauge size={18}/><div><span>Load</span><strong>0.12 · 0.08 · 0.03</strong></div></div></div>}{panel==="network"&&<div className="panel-body"><div className="online-banner"><span className="pulse"/>Browser network bridge available</div><div className="net-card"><strong>eth0</strong><p>192.168.1.42 / 24</p><small>Gateway 192.168.1.1 · DNS 1.1.1.1</small></div><div className="net-card"><strong>HTTP fetch</strong><p>Real CORS-allowed requests</p><small>Raw ICMP/TCP sockets are simulated.</small></div></div>}{panel==="settings"&&<div className="panel-body"><div className="settings-row"><div><strong>Persistence</strong><span>Filesystem saved in localStorage</span></div><RefreshIcon/></div><div className="settings-row"><div><strong>Security</strong><span>No host command execution</span></div><Shield size={16}/></div><button className="danger-button" onClick={()=>persist(clone(INITIAL))}><Trash2 size={14}/>Reset filesystem</button></div>}</motion.aside>}</AnimatePresence></main>
    <div className="shortcut-strip"><span><Gauge size={13}/>16 GiB</span><span><HardDrive size={13}/>128 GiB</span><span><Server size={13}/>8 vCPU</span><span><Network size={13}/>192.168.1.42</span><span className="push-right">{active.user}@henry · {active.cwd}</span></div>
    <AnimatePresence>{searchOpen&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setSearchOpen(false)}><div className="search-modal" onClick={e=>e.stopPropagation()}><Search size={17}/><input autoFocus placeholder="Search terminal output…" value={search} onChange={e=>setSearch(e.target.value)}/><span>{filtered.length} matches</span><button onClick={()=>setSearchOpen(false)}><X size={15}/></button></div></motion.div>}</AnimatePresence>
    <AnimatePresence>{editor&&<Editor path={editor.path} content={editor.content} onClose={()=>setEditor(null)} onSave={content=>{const n=clone(fs),t=getNode(n,editor.path);if(t?.type==="file")t.content=content;persist(n);setEditor(null);}}/>}</AnimatePresence>
  </div>;
}
function RefreshIcon(){return <span style={{fontSize:14}}>↻</span>}
function Editor({path,content,onClose,onSave}:{path:string;content:string;onClose:()=>void;onSave:(content:string)=>void}){const [v,setV]=useState(content);return <div className="modal-backdrop"><div className="nano"><div className="nano-title"><span>GNU nano · {path}</span><button onClick={onClose}><X size={15}/></button></div><textarea autoFocus value={v} onChange={e=>setV(e.target.value)}/><div className="nano-footer"><span>^X Exit</span><span>^O Write Out</span><button onClick={()=>onSave(v)}>Save</button></div></div></div>}
